# Generated by Django 3.0.4 on 2020-08-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('out_university', models.CharField(max_length=50)),
                ('out_place', models.CharField(max_length=20)),
                ('research', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('discussion', models.TextField()),
            ],
        ),
    ]
